### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by tayduds07** [demirhanaydin/waterpi-web#1]
Figured this out.

sudo node index.js
_tls_common.js:104
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:104:17)
    at Object.exports.connect (_tls_wrap.js:1047:48)
    at Object.buildBuilder [as mqtts] (/home/pi/waterpi-web-master/waterpi-node/node_modules/aws-iot-device-sdk/device/lib/tls.js:26:21)
    at MqttClient._wrapper [as streamBuilder] (/home/pi/waterpi-web-master/waterpi-node/node_modules/aws-iot-device-sdk/device/index.js:636:33)
    at MqttClient._setupStream (/home/pi/waterpi-web-master/waterpi-node/node_modules/mqtt/lib/client.js:246:22)
    at new MqttClient (/home/pi/waterpi-web-master/waterpi-node/node_modules/mqtt/lib/client.js:227:8)
    at new DeviceClient (/home/pi/waterpi-web-master/waterpi-node/node_modules/aws-iot-device-sdk/device/index.js:639:17)
    at Object.DeviceClient [as device] (/home/pi/waterpi-web-master/waterpi-node/node_modules/aws-iot-device-sdk/device/index.js:216:14)
    at Object.<anonymous> (/home/pi/waterpi-web-master/waterpi-node/device.js:3:21)
    at Module._compile (module.js:643:30)
I get this error when trying to sudo node index.js when I have all the certs in a folder sorry i just realized i put this is wrong branch it should be in the waterpi-node

**Comment by tayduds07** [comment]
I can't get the charts to show up.
